### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [git-elliot/vernet#1]
```
Error detected in pubspec.yaml:

No file or variants found for asset: secrets.json.
```

Could you please take a look?

**Comment by git-elliot** [comment]
I fixed this in new release 1.0.0+7. Should I build and test locally before creating a release?

**Comment by linsui** [comment]
Thanks! Yes, it's better to make sure the release can be built.

**Comment by git-elliot** [comment]
I will keep this in mind before creating next tag.

**Comment by linsui** [comment]
1.0.0+7 builds fine. And please bump the version before creating next tag. Thanks!

**Comment by git-elliot** [comment]
I've fdroidserver and fdroiddata repo working locally. I can test if fdroidserver is building my app correctly by running `fdroid build` but how can I fetch latest code without creating a tag?

**Comment by linsui** [comment]
The commit can be a hash or a branch. You can use main so that it always build against the latest code.

**Comment by git-elliot** [comment]
@linsui flutter is downloaded every time I run `fdroid build`. Is there any way to avoid downloading again and again?

**Comment by linsui** [comment]
We use flutter from the sourceso it will download it every time. You can modify the recipe to use your installed flutter.
