### ISSUE TITLE
Scan button hangs, due to scanning from 1 to 254.

### ISSUE THREAD

**Issue by git-elliot** [git-elliot/vernet#15]
What about putting scan operation in isolate.

**Comment by guyluz11** [comment]
The page should load first and show searching circle until we find the first results.
And for each result we need to refresh the UI.

**Comment by guyluz11** [comment]
Started converting this page to the bloc for better control over the state of the app and it looks like we do need to use isolate.

**Comment by guyluz11** [comment]
Done, the code is in my fork.
Currently it waits for scanning all the IPs and then showing the result using an isolate.

The code can be more responsive and display each IP as it got found but it requires more work.
It requires the isolate and the app to talk on an open port.
I have asked for better implementation here
https://stackoverflow.com/questions/70946882/should-we-ask-for-dart-team-to-add-support-for-returning-stream-from-an-isolate
In case it doesn't get added or new info that I have missed will get revealed in 2 days I will open the pr with my current implementation.
