### ISSUE TITLE
first subnet

### ISSUE THREAD

**Issue by juvilius** [git-elliot/vernet#3]
why is it not permitted to configure "0" as the first subnet to scan?

**Comment by git-elliot** [comment]
If you know little bit of networking then 0 in the last octet is used for network ID and this IP can not be a host IP.

**Comment by juvilius** [comment]
i know very little indeed. what i meant by first subnet was the third number or like you say octet.
long story short, i wasn't able to scan for this IP in my routers network: 192.168.0.100

**Comment by git-elliot** [comment]
First three octets are auto fetched from the routers wifi and the last octet is what you can change as per your need. Valid range for last octet which you can change in settings also _first subnet_ and _last subnet_ is 1 to 254. 0 is reserved for network ID and 255 is reserved for broadcast address.
